version: '3.7'

networks:
  default:
    name: nginx_network
    driver: bridge


volumes:
  flauschiversum:
  flauschiversum-www:
  flauschiversum-cache:

services:
  flauschiversum-build:
    build: docker/flauschiversum-build
    container_name: flauschiversum-build
    volumes:
      - flauschiversum-www:/var/www/flauschiversum/
      - flauschiversum-cache:/var/share/flauschiversum-cache/
      - flauschiversum:/var/share/flauschiversum/

  flauschiversum:
    image: nginx
    container_name: flauschiversum-nginx
    restart: always
    volumes:
      - flauschiversum-www:/usr/share/nginx/html/
    environment:
      - VIRTUAL_PORT=80
      - VIRTUAL_HOST=flauschiversum.de
      - LETSENCRYPT_HOST=flauschiversum.de
      - LETSENCRYPT_EMAIL=letsencrypt@magierdinge.de

  webhook:
    container_name: flauschiversum-webhook
    restart: unless-stopped
    image: staticfloat/docker-webhook
    volumes:
      # Mount this code into /code
      - ./docker/webhook/:/code
      # Mount the docker socket
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WEBHOOK_SECRET=Uth4coovee
      - WEBHOOK_HOOKS_DIR=/code/hooks
      - WEBHOOK_BRANCH_LIST=master
      - VIRTUAL_PORT=80
      - VIRTUAL_HOST=webhook.flauschiversum.de
      - LETSENCRYPT_HOST=webhook.flauschiversum.de
      - LETSENCRYPT_EMAIL=letsencrypt@magierdinge.de
