#!/bin/bash
echo Update Flauschiversum!
cd /flauschiversum
git pull origin master

rm -rf /tmp/flauschiversum/
mkdir /tmp/flauschiversum/

make run &

MAKE_PID=$!
cd /tmp/flauschiversum/; wget -mnH http://localhost:5000/
kill $MAKE_PID

rsync -av --delete /tmp/flauschiversum/ /var/www/flauschiversum/



